export type ConnectionsTypes = {
    benefits: string,
    jobPostingStatus: string,
    workMode: string,
    publishedMonthsAgo: number,
    companyName: string,
    description: string,
    title: string,
    workModeId: number,
    workingDay: string,
    publishedMinutesAgo: number,
    publishedDaysAgo: number,
    educationLevel: string,
    locationId: number,
    applicantsCount: number,
    publishingStatus: string,
    publishedWeeksAgo: number,
    profileimageUrl: string,
    educationLevelId: number,
    companyOverview: string,
    salaryRange: string,
    workingDayId: number,
    employmentType: string,
    salaryRangeId: number,
    hiringManager: string,
    jobId: number,
    companyId: number,
    employmentTypeId: number,
    publishedHoursAgo: number,
    location: string,
    publishedDate: string,
    duties: string

}