export type FeedType = {
    postedWeeksAgo: number,
    postedByUsername: string,
    postedMonthsAgo: number,
    reactionsCount: number,
    postContent: string,
    postId: number,
    postedDaysAgo: number,
    postedMinutesAgo: number,
    postedByName: string,
    commentsCount: number,
    postImagesUrls: string,
    postDate: string,
    profileImageUrl: string,
    status: string,
    postedHoursAgo: number,
    postImages: string[],
    isOwnPost: false,
}